Add handler for creating WebSocket connection
schramm-famm/patches pull request #8
Opened 2020-02-24 00:57 UTC by igorveselinovic

Resolves #7 

The endpoint `/patches/v1/connect/{conversation_id}` creates a WebSocket (WS) connection between a client and `patches`.

Once the connection is upgraded to a WS connection, `patches` starts a goroutine to start handling messages in the WS. Before reading patches from the WS and writing patches to the WS, `patches` expects the first message to be just the token (should this maybe be sent as a JSON object with one `token` field?). `patches` then makes an HTTP request to `heimdall` to validate the token.

If the token is valid, `patches` then starts a `Client` with one goroutine for reading from the WS and one goroutine for writing to the WS. If this is the first client associated with a conversation, then `patches` creates a `Conversation` and makes an HTTP request to `ether` to get the conversation content. For now, this is just stored as a string in memory, and I'm not sure how else to deal with this right now.

The `Broker` struct contains the methods that are responsible for creation/deletion of `Client` structs and `Conversation` structs.

2020-02-24 00:59 UTC, igorveselinovic commented
While making this PR, I realized that after validating the token, but before registering a new `Client`, `patches` needs to make a call to `/ether/v1/conversations/{conversation_id}/users/{user_id}` to validate that the user who made the WS connection is actually in the conversation.

So I'll fix that.

2020-02-27 04:10 UTC, Thao-Tran requested changes

2020-02-27 04:10 UTC, Thao-Tran commented on websockets/broker.go
> +var etherHost = os.Getenv("ETHER_HOST")
```suggestion
var (
	heimdallHost = os.Getenv("HEIMDALL_HOST")
	etherHost = os.Getenv("ETHER_HOST")
)
```

2020-02-27 04:10 UTC, Thao-Tran commented on websockets/client.go
> +		message, ok := <-c.send
```suggestion
	for message, ok := range <-c.send
```

2020-02-27 04:10 UTC, Thao-Tran commented on websockets/conversation.go
> +				return
Should probably log the error. Also would we want to stop the goroutine entirely in this case or just `continue`?

2020-02-27 04:10 UTC, Thao-Tran commented on websockets/conversation.go
> +				return
Same as previous comment.

2020-02-27 04:10 UTC, Thao-Tran commented on websockets/broker.go
> +type Broker struct {
Maybe you can have a `Run` method for `Broker` that runs in a goroutine and just reads from `register` and `unregister` channels so that you don't have to use locking and whatnot. Then, in `StartClient`, you would just send the member and connection to the broker's `register` channel.

2020-02-27 04:10 UTC, Thao-Tran commented on websockets/conversation.go
> +	broker         *Broker
Does a Conversation need to store a Broker?

2020-02-27 04:10 UTC, Thao-Tran commented on websockets/client.go
> +	conversation *Conversation
Like we discussed before, it might be better to just have a `broadcast` channel and a `conversationID` int64 to replace the `conversation` field.

2020-02-27 04:10 UTC, Thao-Tran commented on websockets/conversation.go
> +			c.doc, _ = dmp.PatchApply(patches, c.doc)
Did you purposefully ignore the error since the error handling will be a whole other issue?

2020-02-27 04:10 UTC, Thao-Tran commented on handlers/handlers.go
> +	go env.WSBroker.StartClient(conversationID, c)
Do we not need to respond with any errors if the client isn't able to start?

2020-02-27 19:54 UTC, igorveselinovic commented on websockets/client.go
> +		message, ok := <-c.send
You mean this ?
```suggestion
	for message, ok := <-c.send {
```

2020-02-27 19:58 UTC, Thao-Tran commented on websockets/client.go
> +		message, ok := <-c.send
Oh no sorry I meant this.
```suggestion
	for message, ok := range c.send
```

2020-02-27 19:58 UTC, igorveselinovic commented on websockets/conversation.go
> +			c.doc, _ = dmp.PatchApply(patches, c.doc)
For handling this error, should we maybe just log it and close the WebSocket that sent the "bad" patch for now?

2020-02-27 20:01 UTC, igorveselinovic commented on websockets/client.go
> +		message, ok := <-c.send
You mean this ?
```suggestion
	for message, ok := range c.send {
```

2020-02-27 20:02 UTC, igorveselinovic commented on websockets/conversation.go
> +	broker         *Broker
It does not. Good catch.

2020-02-27 20:05 UTC, igorveselinovic commented on websockets/conversation.go
> +				return
Yeah, should log the error and `continue`. Maybe also shut down the client?

2020-02-27 20:06 UTC, igorveselinovic commented on websockets/client.go
> +	conversation *Conversation
Will do.

2020-02-27 20:07 UTC, Thao-Tran commented on websockets/conversation.go
> +			c.doc, _ = dmp.PatchApply(patches, c.doc)
Yeah that sounds good.

2020-02-27 20:08 UTC, Thao-Tran commented on websockets/conversation.go
> +				return
Yeah true, it'd probably be a good idea to shut down the client too.

2020-02-27 20:09 UTC, Thao-Tran commented on websockets/client.go
> +		message, ok := <-c.send
Haha yeah like the second one.

2020-02-27 20:09 UTC, igorveselinovic commented on websockets/broker.go
> +type Broker struct {
As we talked about, it makes sense, but just for the sake I've time I'll leave it as-is for now.

2020-02-27 20:13 UTC, igorveselinovic commented on handlers/handlers.go
> +	go env.WSBroker.StartClient(conversationID, c)
Correct me if I'm wrong, but at this point, I think the connection has already been upgraded to a WebSocket connection, so I don't know if you can respond.

2020-02-27 20:23 UTC, Thao-Tran commented on handlers/handlers.go
> +	go env.WSBroker.StartClient(conversationID, c)
Okay yeah I actually had no idea so please correct me if I'm wrong haha

2020-02-27 20:38 UTC, igorveselinovic commented on handlers/handlers.go
> +	go env.WSBroker.StartClient(conversationID, c)
Yeah once it upgrades to the WebSocket protocol, it should just use that to communicate, as far as I understand.

2020-02-27 20:41 UTC, Thao-Tran commented on handlers/handlers.go
> +	go env.WSBroker.StartClient(conversationID, c)
Okay cool sounds good. Carry on then.

2020-02-27 22:21 UTC, Thao-Tran approved these changes

2020-02-27 22:49 UTC, merged